### ISSUE TITLE
-D -F not working on linux/Ubuntu 15.10

### ISSUE THREAD

**Issue by lgfausak** [securesocketfunneling/ssf#10]
I have been experimenting with the linux binaries, Ubuntu 15.10,  64 bit, and am having problems with the -D and -F flags.  I've tried the -D (replacing a working ssh configuration).  ssh is working where ssfc is not.  However, the -V and -U flags are working, so forwarding udp (dns) is working.    So, I can use ssh for the tcp part, and ssf for the udp part, but it sure would be nice to use ssf for both.  Is this still under active development?  What can I do to help debug this?  This is really a nice piece of work.  I especially like the -F (and -U -V or course)!

**Comment by securesocketfunneling** [comment]
Hello,

Thank you for your feedback. SOCKS proxy should work as expected. 
What behaviour do you observe when you connect the client to the server ? Could you post client and server output ?

> Is this still under active development?

SSF is still in active development indeed. There are not many activities right now but we have cool features in the pipe.
A new network framework will be pushed soon and it will replace the connection part of SSF :)

**Comment by lgfausak** [comment]
Hi,

I see that this is stuck in my drafts queue, sorry :-)

The behavior I see is that for tcp/ip I have to use ssh to create my socks
tunnel, and ssf for the udp tunnel.  I can't do both with ssf.

Ah, but I found the issue.  I was trying to curl via socks5h://, when it
should have been socks://.  I guess ssh was giving me a socks5 server, and
ssf was giving me a socks4 server.


-g




On Tue, Feb 16, 2016 at 4:57 AM, securesocketfunneling <
notifications@github.com> wrote:

> Hello,
>
> Thank you for your feedback. SOCKS proxy should work as expected.
> What behaviour do you observe when you connect the client to the server ?
> Could you post client and server output ?
>
> Is this still under active development?
>
> SSF is still in active development indeed. There are not many activities
> right now but we have cool features in the pipe.
> A new network framework will be pushed soon and it will replace the
> connection part of SSF :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/securesocketfunneling/ssf/issues/10#issuecomment-184627867>
> .
>



-- 
Greg Fausak
lgfausak@gmail.com
