### ISSUE TITLE
Error when running ssfs on Ubuntu 14.04 

### ISSUE THREAD

**Issue by nodje** [securesocketfunneling/ssf#13]
Just using the existing binary ssf-linux-x86_64-1.1.0.zip, executing ``ssfc`` produces the following error:
``/ssfc: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./ssfc)``

The machine is std Ubuntu 14.04, up to date. Latest ``libstdc++6`` which I believe provides GLIBC is installed.

**Comment by securesocketfunneling** [comment]
Thanks for the feedback. There is indeed a link issue with the Linux binaries available.
We are currently working on externalizing the network layer with SSF framework but this link issue is one of our top priority next.
The new network layer seems to work pretty well and its integration just needs a little more tests.

This year's beginning is quite hard for us (not enough time and too many things to do). We will try to be more reactive in the future.

Thanks again for your report. It is really appreciated.

**Comment by securesocketfunneling** [comment]
Version 2.1.0 is now out and binaries are available [on the website](https://securesocketfunneling.github.io/ssf/#download).

This new version should fixed your dynamic link issue.
Do not hesitate to give us feedback.
