### ISSUE TITLE
Website download section broken

### ISSUE THREAD

**Issue by davidfavor** [securesocketfunneling/ssf#15]
https://securesocketfunneling.github.io/ssf/#download is slightly broken.

When connecting to download link through a proxy/socks (like ssf) OS is correctly sensed, meaning that some options are greyed out incorrectly.

Better to leave all options active, so people can download whichever version they prefer.

**Comment by davidfavor** [comment]
I was wrong.

Download link for MacOS is just broken.

MacOS link is greyed out at all times.

Please post a direct link to download MacOS zip file.

Thanks.

**Comment by davidfavor** [comment]
https://securesocketfunneling.github.io/ssf/download/1.1.0/ssf-macosx-x86_64-1.1.0.zip is also broken.

**Comment by securesocketfunneling** [comment]
MacOS links are disabled indeed.
We are not providing Mac binaries at the moment. They should be generated from the sources.

**Comment by davidfavor** [comment]
securesocketfunneling wrote:
> MacOS links are disabled indeed.
> We are not providing Mac binaries at the moment. They should be 
> generated from the sources.

Unfortunately, this is impossible.

See other issue ticket about OSX build break.
