### ISSUE TITLE
Could you add a option to bind the client port on 0.0.0.0 in the ssfc ?

### ISSUE THREAD

**Issue by WuSiYu** [securesocketfunneling/ssf#24]
Just like the `-g` option in `ssh -g -L 6667:localhost:6667 192.168.1.101`.
I create a UDP port forwarding and I notice that I can only access the client port on localhost, but I need to let another device (my phone) to access the client port.
So could you add the option to let the client port can be accessed anywhere?

**Comment by securesocketfunneling** [comment]
Planned for the next release

We may also add a way to specify the listening network interface in the config file.

**Comment by securesocketfunneling** [comment]
We mimic SSH behavior.

To listen on the wildcard interface, you will need the following command line:
`ssfc -g -L :6667:localhost:6667 192.168.1.101`

You can also indicate a specific network listening interface:
`ssfc -g -L 192.168.1.100:6667:localhost:6667 192.168.1.101`

This syntax will be available on all client features (local or remote). (cf. `-h` option).

We are making some final check before tagging the new version and we will release the new binaries :-)
If you want to compile your own, it is available on `develop` branch.

**Comment by securesocketfunneling** [comment]
[2.2.0](https://securesocketfunneling.github.io/ssf/#download) binaries are out.

Feel free to test them and make us feedback.
