### ISSUE TITLE
Server DoS when accepting non-TLS data

### ISSUE THREAD

**Issue by koorg** [securesocketfunneling/ssf#25]
On Linux version 2.1.0 x86_64
Step to reproduce : 
- run server
- netcat to server's port, press enter until disconnected (5 or 6 times)

Symptoms : 
- server is unable to accept any more client, need restart

**Comment by securesocketfunneling** [comment]
Thanks for the feedback, it is really appreciated.
We were planning to release version 2.2.0 this week. Bugfix for this critical issue will be part of it.
We will keep you in the loop.

**Comment by securesocketfunneling** [comment]
[2.2.0](https://securesocketfunneling.github.io/ssf/#download) is out!

It should fix this issue too
