### ISSUE TITLE
SIGTERM doesn't stop a client

### ISSUE THREAD

**Issue by koorg** [securesocketfunneling/ssf#26]
On Linux version 2.1.0 x86_64 : 
Steps to reproduce : 
- start netcat to bind on a port
- connect to it with ssfc
- killall ssfc  (SIGTERM)

Symptoms : 
- clients says "client: stop" but doesn't exit
- need to kill -9 the client to stop it

**Comment by securesocketfunneling** [comment]
Thanks again for your feedback.

Planned for 2.2.0 as well :-)

**Comment by securesocketfunneling** [comment]
[2.2.0](https://securesocketfunneling.github.io/ssf/#download) is out!

It should fix this issue.
