### ISSUE TITLE
Please provide pre-built binary for arm

### ISSUE THREAD

**Issue by vimagick** [securesocketfunneling/ssf#30]
I'm trying to run `ssfc` on Raspberry Pi (arm) to bypass firewall.
However, the build process is very complicated for me.

Thank you!

**Comment by securesocketfunneling** [comment]
Thank you for the feedback.

We never tested the project on ARM platform. But we agree that it would be great to have pre-built binaries for ARM.
We have some features in the pipe before looking for this but we will keep you posted !

**Comment by vimagick** [comment]
👍

**Comment by ogattaz** [comment]
Such a very good goal !

**Comment by persianphilosopher** [comment]
I would like to also voice support for this. RPi is often used these days as a router and it would be terrific to have ssf work on arm.

**Comment by securesocketfunneling** [comment]
Hello,

[SSF 3.0.0](https://github.com/securesocketfunneling/ssf/releases/tag/3.0.0) is out and binaries for Raspberry Pi 2/3 are now available (ssf-arm-linux-gnueabihf).
We are looking forward to hearing feedback from you!

**Comment by vimagick** [comment]
:tada:
