### ISSUE TITLE
why does ssfc ignore  'loc_ip'  in option "-D loc_ip:loc_port"?

### ISSUE THREAD

**Issue by nxtreaming** [securesocketfunneling/ssf#31]
Thanks for this good network tool.

./ssfc -D 1.2.3.4:9000 -p 10000 2.3.4.5

It always listens to 127.0.0.1:9000,  but I wish ssfc listens to 1.2.3.4

Thanks.

**Comment by xrl1** [comment]
Add the -g option:
-g [ --gateway-ports ]                Allow gateway ports. At connection, client will be allowed to specify listening network interface on every services

**Comment by securesocketfunneling** [comment]
Hello,

Thanks for your answer @xrl1 :-)

Gateway ports is not not enabled out the box. You need to enable it by adding the CLI `-g` option or by setting the config `gateway_ports` [file option](https://securesocketfunneling.github.io/ssf/#how-to-configure) on the listener services you need (stream for TCP or datagram for UDP).

Config file example:
```
{
    "ssf": {
        "services": {
            "datagram_listener": {
                "gateway_ports": true
            },
            "stream_listener": {
                "gateway_ports": true
            }
        }
    }
}
```

I hope that will solve your issue.
