### ISSUE TITLE
How to specify socks v4 or v5?

### ISSUE THREAD

**Issue by nxtreaming** [securesocketfunneling/ssf#32]
It seems that ssfc always creates SOCKS V4 Server.
How to change the default SOCKS server to V5?
Thanks

**Comment by securesocketfunneling** [comment]
Hi again,

The SOCKS microservice should handle both SOCKS v4 or v5 requests.

Would you mind giving us more details about your use case ? (SSF cli, socks client used, logs, etc.)

Thank you

**Comment by securesocketfunneling** [comment]
Hi,

We did some test in our side and we found that the SOCKS v5 microservice was not processing the auth methods from the client request properly.
The fix for this bug will be part of version 2.3.

Thanks for your feedback

**Comment by nxtreaming** [comment]
Good job!

-----------------------------------------
Productive. Reliable. Fast.

**Comment by securesocketfunneling** [comment]
Hello again,

The fix is released in [version 3.0.0](https://github.com/securesocketfunneling/ssf/releases/tag/3.0.0).
