### ISSUE TITLE
Question: Possible to run ssfs inside Docker?

### ISSUE THREAD

**Issue by madStEvil** [securesocketfunneling/ssf#36]
Hi guys,

i want to start the the server in a docker container, but it doesn't work.

When i try to run it, i get a "not found" message!
the file all permissions and owner is also correct

on host it works...

i'm newbie so i hope it's my fault and someone give me instructions.

i tested it with alpine image

My steps were:

`[arch-c404 ssf-linux-x86_64-2.2.0]# docker run -it --rm -v /root:/root alpine /bin/ash`
`/ # cd /root/ssf-linux-x86_64-2.2.0/`
`~/ssf-linux-x86_64-2.2.0 # chmod +x ssfs`
`~/ssf-linux-x86_64-2.2.0 # ls -al`
`total 31880`
`drwxr-xr-x    3 root     root          4096 Sep 15 21:47 .`
`drwxr-x---   12 root     root          4096 Mar 12 20:20 ..`
`drwxr-xr-x    3 root     root          4096 Sep 15 21:40 certs`
`-rw-r--r--    1 root     root       8346672 Sep 15 21:26 ssfc`
`-rw-r--r--    1 root     root       8166512 Sep 15 21:30 ssfcp`
`-rwxr-xr-x    1 root     root       8825904 Sep 15 21:34 ssfs`
`-rw-r--r--    1 root     root       2407772 Sep 15 21:26 upx-ssfc`
`-rw-r--r--    1 root     root       2388696 Sep 15 21:30 upx-ssfcp`
`-rw-r--r--    1 root     root       2486324 Sep 15 21:34 upx-ssfs`
`~/ssf-linux-x86_64-2.2.0 # ./ssfs -p 10000`
`/bin/ash: ./ssfs: not found`
`~/ssf-linux-x86_64-2.2.0 # apk add --update bash`
`fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz`
`fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz`
`(1/5) Installing ncurses-terminfo-base (6.0-r7)`
`(2/5) Installing ncurses-terminfo (6.0-r7)`
`(3/5) Installing ncurses-libs (6.0-r7)`
`(4/5) Installing readline (6.3.008-r4)`
`(5/5) Installing bash (4.3.46-r5)`
`Executing bash-4.3.46-r5.post-install`
`Executing busybox-1.25.1-r0.trigger`
`OK: 12 MiB in 16 packages`
`~/ssf-linux-x86_64-2.2.0 # bash`
`[a4136065b018 ssf-linux-x86_64-2.2.0]# ./ssfs `
`bash: ./ssfs: No such file or directory`
`[a4136065b018 ssf-linux-x86_64-2.2.0]# exit`
`~/ssf-linux-x86_64-2.2.0 # exit`
`[arch-c404 ssf-linux-x86_64-2.2.0]# ./ssfs `
`[2017-03-12 21:27:25][info] config[tls]: CA cert path: <./certs/trusted/ca.crt>`
`[2017-03-12 21:27:25][info] config[tls]: cert path: <./certs/certificate.crt>`
`[2017-03-12 21:27:25][info] config[tls]: key path: <./certs/private.key>`
`[2017-03-12 21:27:25][info] config[tls]: key password: <>`
`[2017-03-12 21:27:25][info] config[tls]: dh path: <./certs/dh4096.pem>`
`[2017-03-12 21:27:25][info] config[tls]: cipher suite: <DHE-RSA-AES256-GCM-SHA384>`
`[2017-03-12 21:27:25][info] config[HTTP proxy]: <None>`
`[2017-03-12 21:27:25][info] server: listening on <*:8011>`
`[2017-03-12 21:27:25][info] server: running (Ctrl + C to stop)`

Thank you!

**Comment by madStEvil** [comment]
sry my fail ... 

ssf is linked to gnu libc, alipne linux uses musl libc. 
first i used the ldd tool to got the list of shared libraries from binary.
then i copied these files from ubuntu to alpine.
now it is working!

**Comment by securesocketfunneling** [comment]
Hi again,

We are pleased to know that you find a solution to your problem!
We did our best to have standalone executables but some dependencies are still there.
