### ISSUE TITLE
Create WinXP Binaries

### ISSUE THREAD

**Issue by devBioS** [securesocketfunneling/ssf#39]
The tool is incredibly useful but the project binaries are compiled against windows linker v6.0 whereas support on WindowsXP need to be 5.0.1 

the CMake file for MS compilation has a flag (add_definitions(-D_WIN32_WINNT=0x0501)) but the executables on the websites have linked for v6.0

Best regards

**Comment by securesocketfunneling** [comment]
Hello,

It is planned for 2.3.0 :-)

I think the build should already be possible by indicating the XP toolset when generating the solution with CMake.

Using Visual Studio 2013:
```
cmake .. -T "v120_xp"
```

Using Visual Studio 2015:
```
cmake .. -T "v140_xp"
```

**Comment by securesocketfunneling** [comment]
Hello @devBioS ,

[SSF 3.0.0](https://github.com/securesocketfunneling/ssf/releases/tag/3.0.0) is out and Windows binaries are now XP compatible.

**Comment by Metabool** [comment]
Hey @securesocketfunneling,
Thank you very MUCH! :)

**Comment by devBioS** [comment]
Yeah, thanks a lot @securesocketfunneling, exactly what I needed! Love SSF :-)
