### ISSUE TITLE
Add an error documentation

### ISSUE THREAD

**Issue by madushan1000** [securesocketfunneling/ssf#4]
When I try to run SSF_Server built from source on a 64bit ubuntu host error "[0x00007fe70af14700] [error]   server: network error: no socket could be created" comes and there is no description about it.
If you can add a list of common errors and their causes, that would be great.

**Comment by securesocketfunneling** [comment]
> If you can add a list of common errors and their causes, that would be great.

Great idea ! We will add an FAQ section in the website ASAP. Thank you for the feedback.

Concerning your issue, it seems that there is a problem with the SSL certificates. Did you put them in the default directory as mentioned [in the website](https://securesocketfunneling.github.io/ssf/#how-to-configure) ?

**Comment by madushan1000** [comment]
I downloaded the SSF Linux binary and used certs folder found in there with my custom build version. Now it works fine. Seems like there was something wrong with the files I generated manually.
