### ISSUE TITLE
Send custom Useragent Header (Feature Request)

### ISSUE THREAD

**Issue by gregor-hh** [securesocketfunneling/ssf#41]
Hello again,
maybe it's possible to send a "fake useragent" header in the https request?
some proxys only allow specified useragents (like ua=Mozilla ....).

So it would be awesome if we can set a header in the json config or as a parameter.

Is it possible?

best regards
gregor

**Comment by securesocketfunneling** [comment]
Hello,

You are right, the generated CONNECT request may miss some headers to not be denied by some proxies.
It will be added to 2.3 :-)

Thanks for the request

**Comment by securesocketfunneling** [comment]
Hi again!

We added the `ssf.http_proxy.user_agent` config key in the [version 3.0.0](https://github.com/securesocketfunneling/ssf/releases/tag/3.0.0).
You can now customize the user agent of the CONNECT request.
