### ISSUE TITLE
When will the new version be available? 

### ISSUE THREAD

**Issue by nxtreaming** [securesocketfunneling/ssf#49]
The last version was released  in a year ago.

**Comment by securesocketfunneling** [comment]
Hello @nxtreaming

We are making some adjustments at the moment but release is coming :-)

**Comment by securesocketfunneling** [comment]
Hello @nxtreaming ,

Version 3.0.0 is out.
You can check it out [here](https://github.com/securesocketfunneling/ssf/releases/tag/3.0.0)
