### ISSUE TITLE
Port Forwarding - Can't Change Listener

### ISSUE THREAD

**Issue by jasonmerc** [securesocketfunneling/ssf#98]
In SSH, when forwarding ports, you could do something along the lines of **_ssh foo@bar -R [backslash star colon]8080:localhost:8080_** to tell the listener to accept requests from 0.0.0.0 instead of just localhost.  When I try this syntax in ssf, it throws a syntax error.  When I try to enable gateway ports with -g, it still only has the listener on localhost.

I'd need the listener to be for everything in my setup.  Basically, I'm trying to use ssf to connect a server to a "dumb machine" that has a public IP address, and then any requests made to that dumb machine with the public IP address would be forwarded back to the respective ports of the real server.  Think a reverse tunnel that anyone could access, not just the machine with the public IP itself.

Is there a way to set the listener to be 0.0.0.0 instead of just localhost?

**Comment by jasonmerc** [comment]
Closing issue, not sure what happened but I just typed everything in again and it worked.  Maybe I miswrote something before.  Disregard this Issue.

**Comment by MrAdhit** [comment]
Hey, can you post your command?

**Comment by jasonmerc** [comment]
I've tried multiple commands, they all do the same thing.  An example would be as follows:

ssf -V 10000:localhost:10000 -p 19696 [ssf server address here]

This makes the issue happen.  Instead of 10000, it forwards to 75536, which is 10000 mode than 65536.
________________________________
